version: "3.3"
services:
  broker:
    hostname: rabbit
    image: rabbitmq:latest
    # environment:
    #   - DEFAULT_USER=admin
    #   - DEFAULT_PASS=mypass
    expose:
      - "5672:5672"
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    links:
      - broker
    depends_on:
      - broker

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
