version: "3.3"
services:
  broker:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASS=mypass
    expose:
      - "5672:5672"
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    links:
      - broker
    depends_on:
      - broker
